name: dynagui
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - boost-py
  - epics-base
  - jsonschema
  - matplotlib
  - numexpr
  - numpy
  - pandas
  - pandas-datareader
  - pyepics
  - pyqt
  - pyqtgraph
  - requests
