name: dynagui
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - boost-py
  - epics-base
  - functools
  - jsonschema
  - matplotlib
  - numexpr
  - numpy
  - pandas
  - pandas-datareader
  - pyepics
  - pyqt
  - pyqtgraph
  - pytango
  - random
  - requests
  - subprocess
